logging:
  level:
    liquibase: INFO
spring:
  datasource:
    db: add_value_here
    url: add_value_here
    username: add_value_here
    password: add_value_here
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: classpath:/db/db.changelog-master.yaml